/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Cutwidth.MultiOutput.Defs

/-!
# Local linear realizations of a program

A realization assigns a coefficient row to every original circuit wire. Inputs
carry the standard coordinate rows, and each gate row belongs to the linear span
of its original argument rows. The field may be finite or infinite.
-/

@[expose] public section

namespace Algebraic.Cutwidth.MultiOutput.Linear

/-- A coefficient certificate that respects the original program's local dependencies. -/
structure Realization {σ : Signature} {n s : ℕ} (p : Program σ n s)
    (F : Type*) [Field F] where
  /-- The linear coefficient row carried by each original wire. -/
  value : Wire n s → (Fin n → F)
  /-- Primary inputs carry their standard coordinate rows. -/
  input : ∀ j, value (.input j) = Pi.single j 1
  /-- Every gate row is generated by the rows on its original input slots. -/
  gate : ∀ g, value (.gate g) ∈ Submodule.span F
    (Set.range fun i => value ((p.lines g).wires i))

end Algebraic.Cutwidth.MultiOutput.Linear
