/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Cutwidth.MultiOutput.Linear.Defs
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic

/-!
# Field-independent rank bounds from local linear realizations

Across a wire cut, every exterior row restricted to the interior primary inputs
lies in the span of the forward signal rows. The two directed block ranks are
therefore bounded by their respective signal counts, over any field.
-/

@[expose] public section

namespace Algebraic.Cutwidth.MultiOutput.Linear

open SingleCut
open scoped Classical

variable {σ : Signature} {F : Type*} [Field F] {n s m : ℕ}

/-- An exterior wire's interior-input coefficients are generated by the forward signals. -/
theorem Realization.restrict_mem_span_forward {p : Program σ n s}
    (r : Realization p F) (S : Finset (Wire n s)) (wire : Wire n s)
    (outside : wire ∉ S) :
    (fun j : inputsIn S => r.value wire j.val) ∈ Submodule.span F
      (Set.range fun w : forward p S => fun j : inputsIn S => r.value w.val j.val) := by
  let project : (Fin n → F) →ₗ[F] (inputsIn S → F) :=
    { toFun := fun row j => row j.val
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
  let B := Submodule.span F
    (Set.range fun w : forward p S => fun j : inputsIn S => r.value w.val j.val)
  change project (r.value wire) ∈ B
  induction index : wire.index.val using Nat.strong_induction_on generalizing wire with
  | _ k ih =>
    subst index
    cases wire with
    | input i =>
      have zero : project (r.value (.input i)) = 0 := by
        rw [r.input]
        ext j
        have different : j.val ≠ i := by
          intro same
          apply outside
          rw [← same]
          exact mem_inputsIn.mp j.property
        simp [project, different]
      rw [zero]
      exact B.zero_mem
    | gate g =>
      apply (show Submodule.span F (Set.range fun i => r.value ((p.lines g).wires i)) ≤
        B.comap project from Submodule.span_le.mpr ?_) (r.gate g)
      rintro _ ⟨i, rfl⟩
      change project (r.value ((p.lines g).wires i)) ∈ B
      by_cases inside : (p.lines g).wires i ∈ S
      · have crossing : (p.lines g).wires i ∈ forward p S :=
          mem_forward.mpr ⟨inside, g, outside, i, rfl⟩
        exact Submodule.subset_span ⟨⟨(p.lines g).wires i, crossing⟩, rfl⟩
      · exact ih _ (p.lines_wires_lt g i) _ inside rfl

/-- One directed matrix block has rank at most the number of forward signals. -/
theorem Realization.blockRank_le_forward {p : Program σ n s}
    (r : Realization p F) (out : Fin m → Wire n s) (M : Matrix (Fin m) (Fin n) F)
    (rows : ∀ i, r.value (out i) = M i) (S : Finset (Wire n s)) :
    blockRank M (outputsIn out S)ᶜ (inputsIn S) ≤ (forward p S).card := by
  let B := Submodule.span F
    (Set.range fun w : forward p S => fun j : inputsIn S => r.value w.val j.val)
  have contained : Submodule.span F
      (Set.range (M.submatrix (fun i : ↥((outputsIn out S)ᶜ) => i.val)
        (fun j : inputsIn S => j.val)).row) ≤ B := by
    apply Submodule.span_le.mpr
    rintro _ ⟨i, rfl⟩
    have outside : out i.val ∉ S := by
      simpa only [Finset.mem_compl, outputsIn, Finset.mem_filter, Finset.mem_univ,
        true_and] using i.property
    have member := r.restrict_mem_span_forward S (out i.val) outside
    change (fun j : inputsIn S => M i.val j.val) ∈ B
    simpa only [rows i.val] using member
  rw [blockRank, Matrix.rank_eq_finrank_span_row]
  exact (Submodule.finrank_mono contained).trans
    (by simpa only [B, Set.finrank, Fintype.card_coe] using
      (finrank_range_le_card (R := F)
        (fun w : forward p S => fun j : inputsIn S => r.value w.val j.val)))

/-- The opposite directed block is bounded by the backward signals. -/
theorem Realization.blockRank_le_backward {p : Program σ n s}
    (r : Realization p F) (out : Fin m → Wire n s) (M : Matrix (Fin m) (Fin n) F)
    (rows : ∀ i, r.value (out i) = M i) (S : Finset (Wire n s)) :
    blockRank M (outputsIn out S) (inputsIn S)ᶜ ≤ (backward p S).card := by
  have output_compl : outputsIn out Sᶜ = (outputsIn out S)ᶜ := by
    ext i
    simp [outputsIn]
  simpa only [output_compl, inputsIn_compl, forward_compl, compl_compl] using
    r.blockRank_le_forward out M rows Sᶜ

/-- Local linear coefficients give the rank-cut inequality over arbitrary fields. -/
theorem Realization.blockRank_add_blockRank_le {p : Program σ n s}
    (r : Realization p F) (out : Fin m → Wire n s) (M : Matrix (Fin m) (Fin n) F)
    (rows : ∀ i, r.value (out i) = M i) (S : Finset (Wire n s)) :
    blockRank M (outputsIn out S)ᶜ (inputsIn S) +
        blockRank M (outputsIn out S) (inputsIn S)ᶜ ≤
      (forward p S).card + (backward p S).card :=
  Nat.add_le_add (r.blockRank_le_forward out M rows S)
    (r.blockRank_le_backward out M rows S)

/-- A totally regular square output matrix requires distinct original output wires. -/
theorem Realization.outputs_injective {p : Program σ n s} (r : Realization p F)
    (out : Fin n → Wire n s) {M : Matrix (Fin n) (Fin n) F}
    (regular : TotallyRegular M) (rows : ∀ i, r.value (out i) = M i) :
    Function.Injective out := by
  intro i j same
  by_contra different
  have row : M i = M j := (rows i).symm.trans ((congrArg r.value same).trans (rows j))
  have injective : Function.Injective ![i, j] := by
    intro a b equal
    fin_cases a <;> fin_cases b <;> simp_all [eq_comm]
  have nonzero := regular 2 ![i, j] ![i, j] injective injective
  apply nonzero
  rw [Matrix.det_fin_two]
  simp only [Matrix.submatrix_apply, Matrix.cons_val_zero, Matrix.cons_val_one]
  rw [congrFun row i, congrFun row j]
  ring

end Algebraic.Cutwidth.MultiOutput.Linear
