name = "complexitylib"
version = "0.1.0"
defaultTargets = ["Complexitylib"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1cae91f0957ccf8847f22a6239fa0c032a9e28c6"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "94ea80f41a5678fce997a004f0d8d12dbe47cc4b"

[[lean_lib]]
name = "Complexitylib"
