/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Models.TuringMachine.Witness.Store.Defs
import Complexitylib.Models.TuringMachine.Witness.Store.Internal

/-!
# Charged finite certificate materialization

The bounded guess phase produces every certificate of length at most a stored
unary bound and no longer certificate. It preserves unrelated tapes, consumes
its read-only external stream, and accounts for its reusable certificate tape
with an explicit projected all-prefix space bound.
-/

public section

namespace Complexity
namespace WitnessTM

/-- Every stream run stores a bounded canonical witness, with explicit frames. -/
theorem storeBounded_hoareTime (witness counter : Fin k) (hne : witness ≠ counter)
    (B : ℕ) (inp : Tape) (work : Fin k → Tape) (out source : Tape)
    (hwitness : work witness = (Tape.init []).move Dir3.right)
    (hcounter : (work counter).HasUnaryCounter B)
    (hinput : inp.read ≠ Γ.start) (houtput : out.read ≠ Γ.start)
    (hother : ∀ i, i ≠ witness → i ≠ counter → (work i).read ≠ Γ.start)
    (hsource : source.StartInvariant) (hhead : 1 ≤ source.head) :
    (storeBounded witness counter).machine.HoareTime
      (storeEntry inp work out source) (storePost witness counter B inp work out source)
      (NTM.guessBoundedTime B 0) :=
  storeBounded_hoareTime_internal witness counter hne B inp work out source
    hwitness hcounter hinput houtput hother hsource hhead

/-- Every bounded finite certificate is generated by an external Boolean stream. -/
theorem storeBounded_generates (witness counter : Fin k) (hne : witness ≠ counter)
    (B : ℕ) (inp : Tape) (work : Fin k → Tape) (out : Tape)
    (hwitness : work witness = (Tape.init []).move Dir3.right)
    (hcounter : (work counter).HasUnaryCounter B)
    (y : List Bool) (hy : y.length ≤ B) :
    ∃ (g : ℕ → Bool) (c' : Cfg (k + 1) (storeBounded witness counter).machine.Q) (t : ℕ),
      t ≤ NTM.guessBoundedTime B 0 ∧
      (storeBounded witness counter).machine.reachesIn t
        ⟨(storeBounded witness counter).machine.qstart, inp,
          Fin.snoc work (NTM.loadTape g), out⟩ c' ∧
      (storeBounded witness counter).machine.halted c' ∧
      c'.work witness.castSucc = (Tape.init (y.map Γ.ofBool)).move Dir3.right :=
  storeBounded_generates_internal witness counter hne B inp work out hwitness hcounter y hy

/-- The phase stores the certificate in charged space while leaving its source
stream uncharged. The conservative bound depends on `B`, never verifier time. -/
theorem storeBounded_hoareSafety (witness counter : Fin k) (hne : witness ≠ counter)
    (B inputLength initialSpace : ℕ)
    (inp : Tape) (work : Fin k → Tape) (out source : Tape)
    (hwitness : work witness = (Tape.init []).move Dir3.right)
    (hcounter : (work counter).HasUnaryCounter B)
    (hinput : inp.read ≠ Γ.start) (houtput : out.read ≠ Γ.start)
    (hother : ∀ i, i ≠ witness → i ≠ counter → (work i).read ≠ Γ.start)
    (hsource : source.StartInvariant) (hhead : 1 ≤ source.head)
    (hspace : (⟨(), inp, work, out⟩ : Cfg k Unit).WithinDecisionSpace
      inputLength initialSpace) :
    (storeBounded witness counter).machine.HoareSafety (storeEntry inp work out source)
      (fun i w o =>
        (⟨(), i, (fun j => w j.castSucc), o⟩ : Cfg k Unit).WithinDecisionSpace
          inputLength (initialSpace + NTM.guessBoundedTime B 0)) :=
  storeBounded_hoareSafety_internal witness counter hne B inputLength initialSpace
    inp work out source
    hwitness hcounter hinput houtput hother hsource hhead hspace

end WitnessTM
end Complexity
