/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Fusion.Conondeterministic
public import Complexitylib.Algebraic.LowerBound.Fusion.Neq
public import Mathlib.Data.Fintype.Pi

/-!
# A conondeterministic lower bound for Boolean inequality

The false inputs of inequality on two `n`-bit strings are the diagonal
assignments `(v, v)`.  Above a true input `(u, v)`, the two-point family
generated by `(u, u)` and `(v, v)` is a semi-ultrafilter and accepts every
literal true at `(u, v)`.

As in the row/column inequality graph, a pair cover assigns a Boolean code to
every `n`-bit vertex.  Equal codes for distinct vertices would make their
canonical semi-ultrafilter preserve the entire cover.  Thus every cover has at
least `n` pairs.  The universal-circuit pullback transfers this bound, without
loss, to conondeterministic AND/OR circuits over literals.
-/

@[expose] public section

namespace Algebraic
namespace Fusion
namespace Conondeterministic
namespace Neq

noncomputable section

/-- An `n`-bit vertex. -/
abbrev Vertex (n : Nat) := Fin n → Bool

/-- A primary assignment consists of two `n`-bit vertices. -/
abbrev Assignment (n : Nat) := Fin (n + n) → Bool

/-- The left half of a primary assignment. -/
def left (assignment : Assignment n) : Vertex n :=
  fun input => assignment (Fin.castAdd n input)

/-- The right half of a primary assignment. -/
def right (assignment : Assignment n) : Vertex n :=
  fun input => assignment (Fin.natAdd n input)

/-- Pair two vertices into one primary assignment. -/
def pair (leftVertex rightVertex : Vertex n) : Assignment n :=
  combine leftVertex rightVertex

@[simp] theorem left_pair
    (leftVertex rightVertex : Vertex n) :
    left (pair leftVertex rightVertex) = leftVertex := by
  funext input
  simp [left, pair]

@[simp] theorem right_pair
    (leftVertex rightVertex : Vertex n) :
    right (pair leftVertex rightVertex) = rightVertex := by
  funext input
  change Fin.addCases leftVertex rightVertex (Fin.natAdd n input) =
    rightVertex input
  exact Fin.addCases_right input

/-- Boolean inequality of the two halves of a primary assignment. -/
def function (n : Nat) (assignment : Assignment n) : Bool :=
  decide (left assignment ≠ right assignment)

@[simp] theorem function_pair
    (leftVertex rightVertex : Vertex n) :
    function n (pair leftVertex rightVertex) =
      decide (leftVertex ≠ rightVertex) := by
  simp [function]

theorem pair_mem_target_iff
    (leftVertex rightVertex : Vertex n) :
    pair leftVertex rightVertex ∈ (literalProblem (function n)).target ↔
      leftVertex ≠ rightVertex := by
  simp [function]

/-- A diagonal false input, regarded as a point outside inequality. -/
def diagonal (vertex : Vertex n) :
    Problem.Outside (literalProblem (function n)) :=
  ⟨pair vertex vertex, by simp⟩

@[simp] theorem diagonal_value (vertex : Vertex n) :
    (diagonal vertex : Assignment n) = pair vertex vertex := rfl

/-- The canonical two-point semi-filter above an unequal primary input. -/
abbrev canonicalFilter (leftVertex rightVertex : Vertex n) :
    Semifilter (Problem.Outside (literalProblem (function n))) :=
  Semifilter.twoPoint (diagonal leftVertex) (diagonal rightVertex)

/-- The canonical filter accepts every coordinate condition true at its
associated pair. -/
theorem canonicalFilter_accepts_coordinate
    (leftVertex rightVertex : Vertex n)
    (coordinate : Fin (n + n))
    (value : Bool)
    (present : pair leftVertex rightVertex coordinate = value) :
    (literalProblem (function n)).restrict
        { assignment | assignment coordinate = value } ∈
      canonicalFilter leftVertex rightVertex := by
  rw [Semifilter.mem_twoPoint]
  refine Fin.addCases (motive := fun coordinate =>
    pair leftVertex rightVertex coordinate = value →
      (diagonal leftVertex ∈
          (literalProblem (function n)).restrict
            { assignment | assignment coordinate = value }) ∨
        diagonal rightVertex ∈
          (literalProblem (function n)).restrict
            { assignment | assignment coordinate = value })
      (fun input present => ?_) (fun input present => ?_)
      coordinate present
  · left
    rw [Problem.mem_restrict]
    simpa [pair] using present
  · right
    rw [Problem.mem_restrict]
    change pair rightVertex rightVertex (Fin.natAdd n input) = value
    simpa only [pair, combine, Fin.addCases_right] using present

/-- The canonical two-point filter is above its unequal assignment. -/
theorem canonicalFilter_above
    (leftVertex rightVertex : Vertex n) :
    (canonicalFilter leftVertex rightVertex).Above
      (problem := literalProblem (function n))
      (pair leftVertex rightVertex) := by
  intro literal present
  refine Fin.addCases (motive := fun literal =>
    pair leftVertex rightVertex ∈
        (literalProblem (function n)).inputs literal →
      (literalProblem (function n)).restrict
          ((literalProblem (function n)).inputs literal) ∈
        canonicalFilter leftVertex rightVertex)
      (fun coordinate present => ?_)
      (fun coordinate present => ?_) literal present
  · rw [literalProblem_inputs_castAdd] at present ⊢
    exact canonicalFilter_accepts_coordinate
      leftVertex rightVertex coordinate true present
  · rw [literalProblem_inputs_natAdd] at present ⊢
    exact canonicalFilter_accepts_coordinate
      leftVertex rightVertex coordinate false present

/-- Canonical inequality witnesses are semi-ultrafilters. -/
theorem canonicalFilter_isUltra
    (leftVertex rightVertex : Vertex n) :
    (canonicalFilter leftVertex rightVertex).IsUltra :=
  Semifilter.twoPoint_isUltra _ _

/-- Boolean membership code assigned to a diagonal vertex by a pair cover. -/
def coverCode
    (cover : PairCover
      (literalProblem (function n)) SemifilterClass.ultra)
    (vertex : Vertex n) : Fin cover.pairs.length → Bool :=
  fun index => AndOr.membership (diagonal vertex)
    (cover.pairs.get index).1

/-- Every semi-ultrafilter pair cover assigns distinct codes to distinct
Boolean vertices. -/
theorem coverCode_injective
    (cover : PairCover
      (literalProblem (function n)) SemifilterClass.ultra) :
    Function.Injective (coverCode cover) := by
  classical
  intro leftVertex rightVertex codesEqual
  by_contra different
  have targetPresent : pair leftVertex rightVertex ∈
      (literalProblem (function n)).target :=
    (pair_mem_target_iff leftVertex rightVertex).mpr different
  have somePairFails := cover.isCover
    (pair leftVertex rightVertex) targetPresent
    (canonicalFilter leftVertex rightVertex)
    (canonicalFilter_isUltra leftVertex rightVertex)
    (canonicalFilter_above leftVertex rightVertex)
  apply somePairFails
  intro candidate candidatePresent
  obtain ⟨index, pairAtIndex⟩ := List.mem_iff_get.mp candidatePresent
  rw [← pairAtIndex]
  apply Semifilter.twoPoint_preservesPair_of_left_iff
  have bitEqual := congrFun codesEqual index
  exact (AndOr.membership_points_eq_iff
    (diagonal leftVertex) (diagonal rightVertex) _).mp bitEqual

/-- Information-theoretic inequality for semi-ultrafilter covers. -/
theorem two_pow_le_two_pow_cost
    (cover : PairCover
      (literalProblem (function n)) SemifilterClass.ultra) :
    2 ^ n ≤ 2 ^ cover.cost := by
  have cardinality := Fintype.card_le_of_injective
    (coverCode cover) (coverCode_injective cover)
  simpa [PairCover.cost] using cardinality

/-- Every semi-ultrafilter pair cover for Boolean inequality has at least
`n` pairs. -/
theorem ultraPairCover_cost_lowerBound
    (cover : PairCover
      (literalProblem (function n)) SemifilterClass.ultra) :
    n ≤ cover.cost := by
  apply (Nat.pow_le_pow_iff_right (by decide : 2 ≤ 2)).mp
  exact two_pow_le_two_pow_cost cover

/-- Any conondeterministic literal circuit universally computing inequality
of two `n`-bit strings contains at least `n` AND gates, regardless of the
number of auxiliary variables or free OR gates. -/
theorem and_lowerBound
    (circuit : Circuit AndOr.signature
      (((n + n) + a) + ((n + n) + a)) g 1)
    (computes : UniversallyComputes circuit (function n)) :
    n ≤ circuit.cost AndOr.andCost :=
  Conondeterministic.and_lowerBound
    ultraPairCover_cost_lowerBound circuit computes

end

end Neq
end Conondeterministic
end Fusion
end Algebraic
