/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Fusion.Semifilter

/-!
# Boolean interfaces to set-theoretic fusion

An AND/OR circuit over subsets can be evaluated pointwise as a Boolean
circuit.  This file packages that correspondence in both directions and gives
canonical set problems for positive variables and for positive/negative
literals.

The literal construction deliberately models negations at the inputs.  It
does not silently identify arbitrary internal-NOT De Morgan circuits with
bottom-negation circuits; such a conversion belongs in a separate translation
module together with its explicit cost bound.
-/

@[expose] public section

namespace Algebraic
namespace Fusion

noncomputable section

/-- Pointwise Boolean values of the generators in a set problem. -/
abbrev Problem.membershipInput
    (problem : SetProblem Γ)
    (point : Γ) : Fin problem.inputCount → Bool :=
  fun input => AndOr.membership point (problem.inputs input)

@[simp] theorem Problem.membershipInput_apply
    (problem : SetProblem Γ)
    (point : Γ)
    (input : Fin problem.inputCount) :
    problem.membershipInput point input =
      AndOr.membership point (problem.inputs input) := rfl

/-- A Boolean circuit computes the pointwise membership function of a set
problem. -/
def Problem.ComputesMembership
    (problem : SetProblem Γ)
    (circuit : Circuit AndOr.signature problem.inputCount g 1) : Prop :=
  ∀ point,
    circuit.eval AndOr.boolInterpretation (problem.membershipInput point) 0 =
      AndOr.membership point problem.target

/-- Pointwise Boolean computation is equivalent to constructing the target
set from the generator sets. -/
theorem Problem.computesMembership_iff_constructs
    (problem : SetProblem Γ)
    (circuit : Circuit AndOr.signature problem.inputCount g 1) :
    problem.ComputesMembership circuit ↔
      problem.Constructs circuit (AndOr.setInterpretation Γ) := by
  classical
  constructor
  · intro computes
    apply Set.ext
    intro point
    rw [← AndOr.membership_eq_iff]
    have commutes := congrFun
      (circuit.map_eval (AndOr.membershipHomomorphism point) problem.inputs) 0
    have inputMap :
        (AndOr.membershipHomomorphism point).map ∘ problem.inputs =
          problem.membershipInput point := by
      funext input
      rfl
    calc
      AndOr.membership point (circuit.eval (AndOr.setInterpretation Γ)
          problem.inputs 0) =
          circuit.eval AndOr.boolInterpretation
            (problem.membershipInput point) 0 := by
        simpa [inputMap] using commutes
      _ = AndOr.membership point problem.target := computes point
  · intro constructs point
    have commutes := congrFun
      (circuit.map_eval (AndOr.membershipHomomorphism point) problem.inputs) 0
    have inputMap :
        (AndOr.membershipHomomorphism point).map ∘ problem.inputs =
          problem.membershipInput point := by
      funext input
      rfl
    calc
      circuit.eval AndOr.boolInterpretation
          (problem.membershipInput point) 0 =
          AndOr.membership point (circuit.eval (AndOr.setInterpretation Γ)
            problem.inputs 0) := by
        simpa [inputMap] using commutes.symm
      _ = AndOr.membership point problem.target := by rw [constructs]

/-- A pair-cover lower bound applies directly to a circuit computing the
pointwise membership function. -/
theorem pairCover_lowerBound_of_computesMembership
    (problem : SetProblem Γ)
    (admissible : SemifilterClass problem)
    (coverLowerBound : ∀ cover : PairCover problem admissible,
      L ≤ cover.cost)
    (circuit : Circuit AndOr.signature problem.inputCount g 1)
    (computes : problem.ComputesMembership circuit) :
    L ≤ circuit.cost AndOr.andCost :=
  pairCover_lowerBound problem admissible coverLowerBound circuit
    ((problem.computesMembership_iff_constructs circuit).mp computes)

/-- Pair-cover complexity lower-bounds pointwise Boolean computation. -/
theorem pairCoverComplexity_le_cost_of_computesMembership
    (problem : SetProblem Γ)
    (admissible : SemifilterClass problem)
    (circuit : Circuit AndOr.signature problem.inputCount g 1)
    (computes : problem.ComputesMembership circuit) :
    pairCoverComplexity problem admissible ≤
      circuit.cost AndOr.andCost :=
  pairCoverComplexity_le_cost problem admissible circuit
    ((problem.computesMembership_iff_constructs circuit).mp computes)

/-- The set problem generated by the positive input variables of a Boolean
function. -/
abbrev monotoneProblem
    (function : (Fin n → Bool) → Bool) : SetProblem (Fin n → Bool) where
  inputCount := n
  inputs input := { assignment | assignment input = true }
  target := { assignment | function assignment = true }

@[simp] theorem monotoneProblem_membershipInput
    (function : (Fin n → Bool) → Bool)
    (assignment : Fin n → Bool) :
    (monotoneProblem function).membershipInput assignment = assignment := by
  funext input
  exact AndOr.membership_setOf_bool_eq_true assignment
    (fun assignment => assignment input)

theorem monotoneProblem_target_membership
    (function : (Fin n → Bool) → Bool)
    (assignment : Fin n → Bool) :
    AndOr.membership assignment (monotoneProblem function).target =
      function assignment := by
  exact AndOr.membership_setOf_bool_eq_true assignment function

/-- Constructing the positive-generator set problem is exactly computing the
Boolean function with an AND/OR circuit. -/
theorem monotoneProblem_computesMembership_iff
    (function : (Fin n → Bool) → Bool)
    (circuit : Circuit AndOr.signature n g 1) :
    (monotoneProblem function).ComputesMembership circuit ↔
      ∀ assignment,
        circuit.eval AndOr.boolInterpretation assignment 0 =
          function assignment := by
  unfold Problem.ComputesMembership
  constructor
  · intro computes assignment
    calc
      circuit.eval AndOr.boolInterpretation assignment 0 =
          circuit.eval AndOr.boolInterpretation
            ((monotoneProblem function).membershipInput assignment) 0 :=
        congrArg (fun input =>
          circuit.eval AndOr.boolInterpretation input 0)
            (monotoneProblem_membershipInput function assignment).symm
      _ = AndOr.membership assignment (monotoneProblem function).target :=
        computes assignment
      _ = function assignment :=
        monotoneProblem_target_membership function assignment
  · intro computes assignment
    calc
      circuit.eval AndOr.boolInterpretation
          ((monotoneProblem function).membershipInput assignment) 0 =
          circuit.eval AndOr.boolInterpretation assignment 0 :=
        congrArg (fun input =>
          circuit.eval AndOr.boolInterpretation input 0)
            (monotoneProblem_membershipInput function assignment)
      _ = function assignment := computes assignment
      _ = AndOr.membership assignment (monotoneProblem function).target :=
        (monotoneProblem_target_membership function assignment).symm

/-- A semi-filter cover bound for the positive-generator problem transfers
directly to a monotone AND/OR circuit lower bound. -/
theorem monotone_pairCover_lowerBound
    (function : (Fin n → Bool) → Bool)
    (admissible : SemifilterClass (monotoneProblem function))
    (coverLowerBound : ∀ cover :
      PairCover (monotoneProblem function) admissible,
        L ≤ cover.cost)
    (circuit : Circuit AndOr.signature n g 1)
    (computes : ∀ assignment,
      circuit.eval AndOr.boolInterpretation assignment 0 =
        function assignment) :
    L ≤ circuit.cost AndOr.andCost :=
  pairCover_lowerBound_of_computesMembership
    (monotoneProblem function) admissible coverLowerBound circuit
      ((monotoneProblem_computesMembership_iff function circuit).mpr computes)

/-- Positive-generator pair-cover complexity lower-bounds monotone AND/OR
computation. -/
theorem monotone_pairCoverComplexity_le_cost
    (function : (Fin n → Bool) → Bool)
    (admissible : SemifilterClass (monotoneProblem function))
    (circuit : Circuit AndOr.signature n g 1)
    (computes : ∀ assignment,
      circuit.eval AndOr.boolInterpretation assignment 0 =
        function assignment) :
    pairCoverComplexity (monotoneProblem function) admissible ≤
      circuit.cost AndOr.andCost :=
  pairCoverComplexity_le_cost_of_computesMembership
    (monotoneProblem function) admissible circuit
      ((monotoneProblem_computesMembership_iff function circuit).mpr computes)

/-- Literal values associated with an assignment: positive variables first,
then their negations. -/
def literalInput
    (assignment : Fin n → Bool) : Fin (n + n) → Bool :=
  Fin.addCases assignment (fun input => !assignment input)

/-- The set problem generated by both positive and negative literals of a
Boolean function. -/
abbrev literalProblem
    (function : (Fin n → Bool) → Bool) : SetProblem (Fin n → Bool) where
  inputCount := n + n
  inputs := Fin.addCases
    (fun input => { assignment | assignment input = true })
    (fun input => { assignment | assignment input = false })
  target := { assignment | function assignment = true }

theorem literalProblem_inputs_castAdd
    (function : (Fin n → Bool) → Bool)
    (input : Fin n) :
    (literalProblem function).inputs (Fin.castAdd n input) =
      { assignment | assignment input = true } := by
  unfold literalProblem
  change Fin.addCases
    (fun positive : Fin n =>
      { assignment : Fin n → Bool | assignment positive = true })
    (fun negative : Fin n =>
      { assignment : Fin n → Bool | assignment negative = false })
    (Fin.castAdd n input) =
      { assignment | assignment input = true }
  exact Fin.addCases_left input

theorem literalProblem_inputs_natAdd
    (function : (Fin n → Bool) → Bool)
    (input : Fin n) :
    (literalProblem function).inputs (Fin.natAdd n input) =
      { assignment | assignment input = false } := by
  unfold literalProblem
  change Fin.addCases
    (fun positive : Fin n =>
      { assignment : Fin n → Bool | assignment positive = true })
    (fun negative : Fin n =>
      { assignment : Fin n → Bool | assignment negative = false })
    (Fin.natAdd n input) =
      { assignment | assignment input = false }
  exact Fin.addCases_right input

theorem literalInput_natAdd
    (assignment : Fin n → Bool)
    (input : Fin n) :
    literalInput assignment (Fin.natAdd n input) = !assignment input := by
  exact Fin.addCases_right input

@[simp] theorem literalInput_castAdd
    (assignment : Fin n → Bool)
    (input : Fin n) :
    literalInput assignment (Fin.castAdd n input) = assignment input := by
  exact Fin.addCases_left input

@[simp] theorem literalProblem_membershipInput
    (function : (Fin n → Bool) → Bool)
    (assignment : Fin n → Bool) :
    (literalProblem function).membershipInput assignment =
      literalInput assignment := by
  funext literal
  refine Fin.addCases (motive := fun literal =>
    (literalProblem function).membershipInput assignment literal =
      literalInput assignment literal) (fun input => ?_)
      (fun input => ?_) literal
  · simp [literalProblem, literalInput]
  · rw [Problem.membershipInput_apply,
      literalProblem_inputs_natAdd, literalInput_natAdd]
    exact AndOr.membership_setOf_bool_eq_false assignment
      (fun assignment => assignment input)

theorem literalProblem_target_membership
    (function : (Fin n → Bool) → Bool)
    (assignment : Fin n → Bool) :
    AndOr.membership assignment (literalProblem function).target =
      function assignment := by
  exact AndOr.membership_setOf_bool_eq_true assignment function

/-- Constructing the literal-generator set problem is exactly computing the
function from its positive and negative literal values. -/
theorem literalProblem_computesMembership_iff
    (function : (Fin n → Bool) → Bool)
    (circuit : Circuit AndOr.signature (n + n) g 1) :
    (literalProblem function).ComputesMembership circuit ↔
      ∀ assignment,
        circuit.eval AndOr.boolInterpretation (literalInput assignment) 0 =
          function assignment := by
  unfold Problem.ComputesMembership
  constructor
  · intro computes assignment
    calc
      circuit.eval AndOr.boolInterpretation (literalInput assignment) 0 =
          circuit.eval AndOr.boolInterpretation
            ((literalProblem function).membershipInput assignment) 0 :=
        congrArg (fun input =>
          circuit.eval AndOr.boolInterpretation input 0)
            (literalProblem_membershipInput function assignment).symm
      _ = AndOr.membership assignment (literalProblem function).target :=
        computes assignment
      _ = function assignment :=
        literalProblem_target_membership function assignment
  · intro computes assignment
    calc
      circuit.eval AndOr.boolInterpretation
          ((literalProblem function).membershipInput assignment) 0 =
          circuit.eval AndOr.boolInterpretation (literalInput assignment) 0 :=
        congrArg (fun input =>
          circuit.eval AndOr.boolInterpretation input 0)
            (literalProblem_membershipInput function assignment)
      _ = function assignment := computes assignment
      _ = AndOr.membership assignment (literalProblem function).target :=
        (literalProblem_target_membership function assignment).symm

/-- A semi-filter cover bound for the literal-generator problem transfers
directly to an AND/OR-over-literals circuit lower bound. -/
theorem literal_pairCover_lowerBound
    (function : (Fin n → Bool) → Bool)
    (admissible : SemifilterClass (literalProblem function))
    (coverLowerBound : ∀ cover :
      PairCover (literalProblem function) admissible,
        L ≤ cover.cost)
    (circuit : Circuit AndOr.signature (n + n) g 1)
    (computes : ∀ assignment,
      circuit.eval AndOr.boolInterpretation (literalInput assignment) 0 =
        function assignment) :
    L ≤ circuit.cost AndOr.andCost :=
  pairCover_lowerBound_of_computesMembership
    (literalProblem function) admissible coverLowerBound circuit
      ((literalProblem_computesMembership_iff function circuit).mpr computes)

/-- Literal-generator pair-cover complexity lower-bounds AND/OR computation
over positive and negative input literals. -/
theorem literal_pairCoverComplexity_le_cost
    (function : (Fin n → Bool) → Bool)
    (admissible : SemifilterClass (literalProblem function))
    (circuit : Circuit AndOr.signature (n + n) g 1)
    (computes : ∀ assignment,
      circuit.eval AndOr.boolInterpretation (literalInput assignment) 0 =
        function assignment) :
    pairCoverComplexity (literalProblem function) admissible ≤
      circuit.cost AndOr.andCost :=
  pairCoverComplexity_le_cost_of_computesMembership
    (literalProblem function) admissible circuit
      ((literalProblem_computesMembership_iff function circuit).mpr computes)

end

end Fusion
end Algebraic
