/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.Basis.SumOfTerms
public import Complexitylib.Algebraic.LowerBound.Fusion.Framework
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# Fusion for sum-of-terms circuits

For a module-valued sum-of-terms circuit, a fusion witness is a submodule that
contains every free input but excludes the target.  Addition preserves such a
witness.  A term gate preserves it exactly when the corresponding dictionary
value lies in the submodule.

It follows that the target belongs to the span of the input values and the
terms occurring in every fusion cover.  This is the algebraic bridge used by
rank, flattening, and partial-derivative lower bounds.
-/

@[expose] public section

namespace Algebraic
namespace Fusion
namespace SumOfTerms

variable {K : Type u} {V : Type v} {T : Type w}
variable [Semiring K] [AddCommMonoid V] [Module K V]

/-- A linear obstruction containing the free inputs but not the target. -/
structure SpanWitness (problem : Problem V) where
  /-- Candidate subspace generated by the available local terms. -/
  submodule : Submodule K V
  /-- Every free circuit input already belongs to the subspace. -/
  inputs_mem : ∀ input, problem.inputs input ∈ submodule
  /-- The desired target does not belong to the subspace. -/
  target_not_mem : problem.target ∉ submodule

/-- Fusion model of linear-span obstructions. -/
def spanModel
    (termValue : T → V)
    (problem : Problem V) :
    Model (Algebraic.SumOfTerms.termCost (T := T))
      (Algebraic.SumOfTerms.interpretation termValue) problem where
  Witness := SpanWitness (K := K) problem
  reference _ _ := True
  observed witness value := value ∈ witness.submodule
  input_sound := by
    intro witness input _
    exact witness.inputs_mem input
  target_reference := by
    intro _
    trivial
  target_not_observed := by
    intro witness
    exact witness.target_not_mem

/-- Addition preserves every linear-span witness. -/
theorem add_preserved
    (termValue : T → V)
    (problem : Problem V)
    (arguments : Fin 2 → V)
    (witness : (spanModel (K := K) termValue problem).Witness) :
    (⟨.add, arguments⟩ :
      Atom (Algebraic.SumOfTerms.signature T) V).PreservedBy
        (spanModel termValue problem) witness := by
  simp only [Atom.PreservedBy, Model.Sound, Atom.result, spanModel,
    Algebraic.SumOfTerms.interpretation, true_implies]
  intro argumentsMem
  exact witness.submodule.add_mem
    (argumentsMem (0 : Fin 2)) (argumentsMem (1 : Fin 2))

/-- A term gate preserves a witness exactly when its value lies in the
witness submodule. -/
theorem term_preserved_iff
    (termValue : T → V)
    (problem : Problem V)
    (term : T)
    (arguments : Fin (Algebraic.SumOfTerms.arity (.term term)) → V)
    (witness : (spanModel (K := K) termValue problem).Witness) :
    (⟨.term term, arguments⟩ :
      Atom (Algebraic.SumOfTerms.signature T) V).PreservedBy
        (spanModel termValue problem) witness ↔
      termValue term ∈ witness.submodule := by
  simp [Atom.PreservedBy, Model.Sound, Atom.result, spanModel,
    Algebraic.SumOfTerms.interpretation]

/-- Retain the dictionary parameter of term atoms and discard additions. -/
def Atom.term?
    (atom : Atom (Algebraic.SumOfTerms.signature T) V) : Option T :=
  match atom with
  | ⟨.add, _⟩ => none
  | ⟨.term term, _⟩ => some term

/-- Dictionary terms occurring in a list of fusion atoms. -/
def terms
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V)) : List T :=
  atoms.filterMap Atom.term?

omit [AddCommMonoid V] in
@[simp] theorem terms_cons_add
    (arguments : Fin 2 → V)
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V)) :
    terms ((⟨.add, arguments⟩ :
      Atom (Algebraic.SumOfTerms.signature T) V) :: atoms) = terms atoms := rfl

omit [AddCommMonoid V] in
@[simp] theorem terms_cons_term
    (term : T)
    (arguments : Fin (Algebraic.SumOfTerms.arity (.term term)) → V)
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V)) :
    terms ((⟨.term term, arguments⟩ :
      Atom (Algebraic.SumOfTerms.signature T) V) :: atoms) =
        term :: terms atoms := rfl

omit [AddCommMonoid V] in
/-- The number of retained terms is exactly the charged atom cost. -/
theorem terms_length
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V)) :
    (terms atoms).length =
      Atom.listCost atoms (Algebraic.SumOfTerms.termCost (T := T)) := by
  induction atoms with
  | nil => rfl
  | cons atom atoms inductionHypothesis =>
      cases atom with
      | mk op arguments =>
          cases op with
          | add =>
              change Fin 2 → V at arguments
              rw [terms_cons_add]
              simpa [Atom.listCost, Atom.cost] using inductionHypothesis
          | term term =>
              rw [terms_cons_term]
              simp [Atom.listCost, Atom.cost, inductionHypothesis,
                Nat.add_comm]

omit [AddCommMonoid V] in
/-- The sum of term-dependent dictionary weights is exactly the corresponding
weighted atom cost. -/
theorem terms_weight_sum
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V))
    (weight : T → Nat) :
    ((terms atoms).map weight).sum =
      Atom.listCost atoms (Algebraic.SumOfTerms.dictionaryCost weight) := by
  induction atoms with
  | nil => rfl
  | cons atom atoms inductionHypothesis =>
      cases atom with
      | mk op arguments =>
          cases op with
          | add =>
              change Fin 2 → V at arguments
              rw [terms_cons_add]
              simpa [Atom.listCost, Atom.cost] using inductionHypothesis
          | term term =>
              rw [terms_cons_term]
              simp [Atom.listCost, Atom.cost, inductionHypothesis]

/-- The submodule generated by free inputs and all terms in an atom list. -/
noncomputable def generatedSubmodule
    (termValue : T → V)
    (problem : Problem V)
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V)) :
    Submodule K V :=
  Submodule.span K
    (Set.range problem.inputs ∪
      Set.range fun index : Fin (terms atoms).length =>
        termValue ((terms atoms).get index))

/-- Every free input belongs to the generated submodule. -/
theorem input_mem_generatedSubmodule
    (termValue : T → V)
    (problem : Problem V)
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V))
    (input : Fin problem.inputCount) :
    problem.inputs input ∈ generatedSubmodule (K := K) termValue problem atoms := by
  apply Submodule.subset_span
  exact Or.inl ⟨input, rfl⟩

/-- A term atom occurring in the list contributes its value to the generated
submodule. -/
theorem termValue_mem_generatedSubmodule
    (termValue : T → V)
    (problem : Problem V)
    (atoms : List (Atom (Algebraic.SumOfTerms.signature T) V))
    (term : T)
    (arguments : Fin (Algebraic.SumOfTerms.arity (.term term)) → V)
    (present : (⟨.term term, arguments⟩ :
      Atom (Algebraic.SumOfTerms.signature T) V) ∈ atoms) :
    termValue term ∈ generatedSubmodule (K := K) termValue problem atoms := by
  have termPresent : term ∈ terms atoms := by
    change term ∈ atoms.filterMap Atom.term?
    rw [List.mem_filterMap]
    exact ⟨⟨.term term, arguments⟩, present, rfl⟩
  obtain ⟨index, indexSpec⟩ := List.mem_iff_get.mp termPresent
  apply Submodule.subset_span
  exact Or.inr ⟨index, by simpa using congrArg termValue indexSpec⟩

/-- Every fusion cover spans the target using its term atoms and free inputs. -/
theorem target_mem_generatedSubmodule
    (termValue : T → V)
    (problem : Problem V)
    (cover : Cover (spanModel (K := K) termValue problem)) :
    problem.target ∈
      generatedSubmodule (K := K) termValue problem cover.atoms := by
  classical
  by_contra targetNotMem
  let witness : SpanWitness (K := K) problem := {
    submodule := generatedSubmodule (K := K) termValue problem cover.atoms
    inputs_mem := input_mem_generatedSubmodule termValue problem cover.atoms
    target_not_mem := targetNotMem
  }
  apply cover.isCover witness
  intro atom present
  cases atom with
  | mk op arguments =>
      cases op with
      | add =>
          change Fin 2 → V at arguments
          exact add_preserved termValue problem arguments witness
      | term term =>
          apply (term_preserved_iff termValue problem term arguments witness).2
          exact termValue_mem_generatedSubmodule termValue problem cover.atoms
            term arguments present

end SumOfTerms
end Fusion
end Algebraic
