/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Models.TuringMachine.Witness.Verifier.Internal.Join

/-!
# Correctness of the ordinary finite-verifier compiler

The initialized prefix and deterministic suffix form one concrete witness
machine. Every stream halts, every accepted run has a permitted certificate,
and every permitted accepting certificate is generated by some stream.
-/

public section

namespace Complexity
/-- A time-bounded deterministic decider obeys the same bound in decision space. -/
theorem TM.decidesInTimeSpace_of_decidesInTime_internal {k : ℕ} {M : TM k}
    {L : Language} {T : ℕ → ℕ} (hM : M.DecidesInTime L T) :
    M.DecidesInTimeSpace L T T := by
  refine ⟨?_, hM⟩
  intro x c hc
  obtain ⟨t, ht⟩ := M.reaches_to_reachesIn hc
  obtain ⟨d, u, hu, hr, hh, _⟩ := hM x
  have htu : t ≤ u := M.reachesIn_le_halt ht hr hh
  obtain ⟨hin, hout, hwork⟩ := M.head_le_of_reachesIn ht
  exact ⟨⟨fun i => (hwork i).trans (htu.trans hu), by omega⟩, by omega⟩


namespace WitnessTM.Verifier

private theorem loaded_entry (r k : ℕ) (x : List Bool) (g : ℕ → Bool) :
    prefixEntry r k x (Tape.init (x.map Γ.ofBool))
      (Fin.snoc (fun _ => Tape.init []) (NTM.loadTape g)) (Tape.init []) := by
  refine ⟨⟨rfl, ?_, rfl⟩, ?_, ?_⟩
  · funext i
    simp
  · simpa using NTM.loadTape_startInvariant g
  · simp

/-- Concrete full-pipeline time and all-reachable projected space contracts. -/
theorem compile_contract_internal (setup : WitnessBoundSetup r bound) (M : TM k)
    {L : Language} {T S : ℕ → ℕ} (hM : M.DecidesInTimeSpace L T S) (x : List Bool) :
    (compile setup M).machine.HoareTime (prefixEntry r k x)
      (fun _ _ out => ∃ y, y.length ≤ bound x.length ∧
        (pair x y ∈ L → out.cells 1 = Γ.one) ∧ (pair x y ∉ L → out.cells 1 = Γ.zero))
      (time setup T x.length) ∧
    (compile setup M).machine.HoareSafety (prefixEntry r k x)
      (fun inp work out =>
        (⟨(), inp, (fun i => work i.castSucc), out⟩ : Cfg (tapes r k) Unit).WithinDecisionSpace
          x.length (space setup S x.length)) := by
  have hprefix := prefix_hoareTime setup k x
  have hsuffix := suffixStage_contract setup M hM x
  have htrans := fun inp work out (h : prefixPost r k x (bound x.length) inp work out) =>
    prefixPost_transition h
  constructor
  · exact (TM.seqTM_hoareTime _ _ hprefix htrans hsuffix.1).mono_bound (by
      unfold time
      omega)
  · have hs : setup.space x.length ≤ space setup S x.length := by unfold space; omega
    have hg : 1 + NTM.guessBoundedTime (bound x.length) 0 ≤ space setup S x.length := by
      unfold space
      omega
    exact TM.seqTM_hoareSafety _ _ hprefix htrans hsuffix.1
      (prefix_hoareSafety setup k x _ hs hg) hsuffix.2

/-- Every completed stream run has the verifier's verdict for a bounded certificate. -/
theorem compile_run_verdict_internal (setup : WitnessBoundSetup r bound) (M : TM k)
    {L : Language} {T S : ℕ → ℕ} (hM : M.DecidesInTimeSpace L T S)
    (x : List Bool) (g : ℕ → Bool) :
    let c := (compile setup M).run x g (time setup T x.length)
    (compile setup M).machine.halted c ∧
      ∃ y, y.length ≤ bound x.length ∧
        (pair x y ∈ L → c.output.cells 1 = Γ.one) ∧
        (pair x y ∉ L → c.output.cells 1 = Γ.zero) := by
  obtain ⟨c, t, ht, hr, hh, hp⟩ := (compile_contract_internal setup M hM x).1
    _ _ _ (loaded_entry r k x g)
  have he : (compile setup M).run x g (time setup T x.length) = c :=
    TM.traceD_of_reachesIn_halted (compile setup M).machine ht hr hh
  change (compile setup M).machine.halted ((compile setup M).run x g _) ∧ _
  rw [he]
  exact ⟨hh, hp⟩

/-- A chosen accepting finite certificate yields an accepting initialized run. -/
theorem compile_accepts_of_certificate_internal (setup : WitnessBoundSetup r bound) (M : TM k)
    {L : Language} {T S : ℕ → ℕ} (hM : M.DecidesInTimeSpace L T S)
    (x y : List Bool) (hy : y.length ≤ bound x.length) (hyes : pair x y ∈ L) :
    (compile setup M).AcceptsInTime x (time setup T x.length) := by
  let P := (guessPrefix setup k).machine
  let D := (ofDeterministic (suffix r M)).machine
  obtain ⟨g, c, t, ht, hr, hh, hstored⟩ := prefix_generates setup k x y hy
  obtain ⟨c₀, t₀, ht₀, hr₀, hh₀, hp₀⟩ := prefix_hoareTime setup k x _ _ _
    (loaded_entry r k x g)
  have heq : c = c₀ :=
    (TM.traceD_of_reachesIn_halted P ht hr hh).symm.trans
      (TM.traceD_of_reachesIn_halted P ht₀ hr₀ hh₀)
  have hp : prefixPost r k x (bound x.length) c.input c.work c.output := heq.symm ▸ hp₀
  have hentry := prefixPost_transition_for y hp hstored
  obtain ⟨d, s, hs, hrd, hhd, hverd⟩ := (liftedSuffix_for setup M hM x y hy).1
    _ _ _ hentry
  have hfull := TM.seqTM_reachesIn_of_reachesIn P D hr hh hrd
  have hhalt := (TM.phase2Wrap_halted_iff P D d).2 hhd
  have htime : t + 1 + s ≤ time setup T x.length := by unfold time; omega
  have he : (compile setup M).run x g (time setup T x.length) = TM.phase2Wrap P D d :=
    TM.traceD_of_reachesIn_halted (compile setup M).machine htime hfull hhalt
  refine ⟨g, ?_, ?_⟩
  · rw [he]
    exact hhalt
  · rw [he]
    exact hverd.1 hyes

/-- The certificate-storing compiler realizes bounded existential verification
with the explicit independent time and charged-space formulas. -/
theorem compile_decidesInTimeSpace_internal (setup : WitnessBoundSetup r bound) (M : TM k)
    {L : Language} {T S : ℕ → ℕ} (hM : M.DecidesInTimeSpace L T S) :
    (compile setup M).DecidesInTimeSpace (language bound L)
      (time setup T) (space setup S) := by
  constructor
  · constructor
    · intro x g
      exact (compile_run_verdict_internal setup M hM x g).1
    · intro x
      constructor
      · rintro ⟨y, hy, hyes⟩
        exact compile_accepts_of_certificate_internal setup M hM x y hy hyes
      · rintro ⟨g, _, hout⟩
        obtain ⟨_, y, hy, _, hno⟩ := compile_run_verdict_internal setup M hM x g
        refine ⟨y, hy, ?_⟩
        by_contra h
        have hz := hno h
        rw [hout] at hz
        exact (by decide : Γ.one ≠ Γ.zero) hz
  · intro x g t _
    obtain ⟨s, _, hr, _⟩ := TM.reachesIn_traceD (compile setup M).machine t
      (NTM.loadCfg (compile setup M).machine x g)
    exact (compile_contract_internal setup M hM x).2 _ _ _ (loaded_entry r k x g) _
      (TM.reaches_of_reachesIn hr)

end WitnessTM.Verifier
end Complexity
