/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Cutwidth.Aggregate.Compressed.Hardness
public import Mathlib.Algebra.Group.Submonoid.Membership

/-!
# The canonical joint register generated by signal contributions

Every aggregate circuit has an unconditional local factorization: take the submonoid
of its register product generated by the two contributions available at every signal.
Its size can be much smaller than the product of the original register sizes.
-/

@[expose] public section

namespace Algebraic.Aggregate.Compressed

variable {J : Type} {State : J → Type} [∀ j, CommMonoid (State j)] {n g : ℕ}

/-- All locally available joint contributions generate a canonical compressed monoid. -/
def generated (p : Program (signature State) n g) : Submonoid (Registers p) :=
  Submonoid.closure (Set.range fun pair : Wire n g × Bool =>
    wireContribution p pair.1 pair.2)

noncomputable instance [∀ j, Fintype (State j)] (p : Program (signature State) n g) :
    Fintype (generated p) := Fintype.ofFinite _

/-- Every circuit factors through its generated joint register, without an extra premise. -/
def generatedFactorization (p : Program (signature State) n g) :
    Factorization p (generated p) where
  contribution wire value := ⟨wireContribution p wire value,
    Submonoid.subset_closure ⟨(wire, value), rfl⟩⟩
  decode := (generated p).subtype
  factor _ _ := rfl

end Algebraic.Aggregate.Compressed

namespace Algebraic.Cutwidth.Aggregate.Compressed

variable {J : Type} {State : J → Type}
  [∀ j, CommMonoid (State j)] [∀ j, Fintype (State j)]

/-- The automatic generated-register instance retains the explicit Gaussian coefficient. -/
theorem sourceReductionHardFamily_eventually_lt_size_generated
    (D : Nat → Nat)
    (hD : (fun n => (D n : ℝ)) =o[Filter.atTop] (fun n => (n : ℝ)))
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ n in Filter.atTop, ∀ c : Circuit (Algebraic.Aggregate.signature State) n 1,
      c.Computes Algebraic.Aggregate.interpretation
        (fun x _ => Extractor.sourceReductionHardFamily n x) →
      Algebraic.Aggregate.Compressed.budget
        (Algebraic.Aggregate.Compressed.generated c.program) ≤ D n →
        (1 + Real.pi / (3 * Real.arccos ((1 + 2 * Real.sqrt 2) / 4)) - ε) * n <
          c.size := by
  filter_upwards [sourceReductionHardFamily_eventually_lt_size_gaussian
    (State := State) D hD hε] with n bound c computes budget
  exact bound _ c (Algebraic.Aggregate.Compressed.generatedFactorization c.program)
    computes budget

end Algebraic.Cutwidth.Aggregate.Compressed
