/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Fusion.Arithmetic.Interaction.Polynomial.Quotient

/-!
# Exact nonlinear coordinates for polynomial quotient Fusion

In the standard `n`-variable polynomial model, every field constant and every
variable is free.  The free-data submodule is therefore the affine-linear
polynomials.  Extract all coefficients except the constant and degree-one
variable coefficients.

This module proves that the joint nonlinear coefficient map has exactly the
affine-linear submodule as its kernel.  Consequently, the rank of the full
nonlinear coefficient matrix of any output family equals—rather than merely
lower-bounds—the canonical quotient-output rank.
-/

@[expose] public section

namespace Algebraic
namespace Fusion
namespace Arithmetic
namespace Interaction
namespace Polynomial
namespace Nonlinear

noncomputable section

variable {K : Type u}

/-- Exponents other than the constant exponent and individual degree-one
variable exponents. -/
abbrev Exponent (n : Nat) : Type :=
  { exponent : Fin n →₀ ℕ //
    exponent ≠ 0 ∧
      ∀ input : Fin n, exponent ≠ Finsupp.single input 1 }

/-- Joint extraction of every nonlinear monomial coefficient. -/
def coefficientFeature
    [Field K]
    (n : Nat) :
    MvPolynomial (Fin n) K →ₗ[K] (Exponent n → K) :=
  Polynomial.coefficientFeature fun exponent : Exponent n => exponent.1

/-- Standard polynomial problem with all variables free. -/
abbrev inputProblem
    (K : Type u)
    [Field K]
    (n : Nat) : Problem (MvPolynomial (Fin n) K) :=
  Polynomial.inputProblem (K := K) (fun input : Fin n => input)

/-- Affine-linear polynomial submodule generated by all constants and
variables. -/
abbrev affineSubmodule
    (K : Type u)
    [Field K]
    (n : Nat) : Submodule K (MvPolynomial (Fin n) K) :=
  Linear.Quotient.freeSubmodule K
    (MvPolynomial.C : K → MvPolynomial (Fin n) K)
    (inputProblem K n)

/-- Every constant polynomial is affine-linear. -/
theorem C_mem_affineSubmodule
    [Field K]
    (n : Nat)
    (scalar : K) :
    MvPolynomial.C scalar ∈ affineSubmodule K n :=
  Linear.Quotient.constant_mem_freeSubmodule
    (MvPolynomial.C : K → MvPolynomial (Fin n) K)
    (inputProblem K n) scalar

/-- Every variable polynomial is affine-linear. -/
theorem X_mem_affineSubmodule
    [Field K]
    (n : Nat)
    (input : Fin n) :
    MvPolynomial.X input ∈ affineSubmodule K n :=
  Linear.Quotient.input_mem_freeSubmodule
    (MvPolynomial.C : K → MvPolynomial (Fin n) K)
    (inputProblem K n) input

/-- A monomial whose exponent is not nonlinear is affine-linear. -/
theorem monomial_mem_affineSubmodule_of_not_nonlinear
    [Field K]
    (n : Nat)
    (exponent : Fin n →₀ ℕ)
    (notNonlinear : ¬ (exponent ≠ 0 ∧
      ∀ input : Fin n, exponent ≠ Finsupp.single input 1))
    (coefficient : K) :
    MvPolynomial.monomial exponent coefficient ∈ affineSubmodule K n := by
  classical
  by_cases exponentZero : exponent = 0
  · subst exponent
    simpa only [MvPolynomial.monomial_zero'] using
      C_mem_affineSubmodule n coefficient
  · have notAllInputs : ¬ ∀ input : Fin n,
        exponent ≠ Finsupp.single input 1 :=
      fun allInputs => notNonlinear ⟨exponentZero, allInputs⟩
    push Not at notAllInputs
    obtain ⟨input, exponentEqual⟩ := notAllInputs
    rw [exponentEqual, ← MvPolynomial.C_mul_X_eq_monomial]
    simpa [Algebra.smul_def, MvPolynomial.algebraMap_eq] using
      (affineSubmodule K n).smul_mem coefficient
        (X_mem_affineSubmodule n input)

/-- Affine-linear polynomials have no nonlinear coefficients. -/
theorem affineSubmodule_le_ker_coefficientFeature
    [Field K]
    (n : Nat) :
    affineSubmodule K n ≤
      LinearMap.ker (coefficientFeature (K := K) n) := by
  dsimp [affineSubmodule, Linear.Quotient.freeSubmodule]
  rw [Submodule.span_le]
  intro polynomial present
  change coefficientFeature (K := K) n polynomial = 0
  rcases present with inputPresent | constantPresent
  · obtain ⟨input, rfl⟩ := inputPresent
    exact Polynomial.coefficientFeature_X_eq_zero
      (fun exponent : Exponent n => exponent.1) input
      (fun exponent => exponent.2.2 input)
  · obtain ⟨scalar, rfl⟩ := constantPresent
    exact Polynomial.coefficientFeature_C_eq_zero
      (fun exponent : Exponent n => exponent.1)
      (fun exponent => exponent.2.1) scalar

/-- Vanishing of every nonlinear coefficient forces a polynomial to be
affine-linear. -/
theorem ker_coefficientFeature_le_affineSubmodule
    [Field K]
    (n : Nat) :
    LinearMap.ker (coefficientFeature (K := K) n) ≤ affineSubmodule K n := by
  classical
  intro polynomial polynomialInKernel
  have featureZero : coefficientFeature (K := K) n polynomial = 0 :=
    LinearMap.mem_ker.mp polynomialInKernel
  rw [polynomial.as_sum]
  apply Submodule.sum_mem
  intro exponent exponentInSupport
  by_cases nonlinear : exponent ≠ 0 ∧
      ∀ input : Fin n, exponent ≠ Finsupp.single input 1
  · have coefficientZero : AddMonoidAlgebra.coeff polynomial exponent = 0 := by
      have pointwise := congrFun featureZero
        (⟨exponent, nonlinear⟩ : Exponent n)
      simpa [coefficientFeature, Polynomial.coefficientFeature] using pointwise
    rw [coefficientZero, MvPolynomial.monomial_zero]
    exact (affineSubmodule K n).zero_mem
  · exact monomial_mem_affineSubmodule_of_not_nonlinear n exponent
      nonlinear (AddMonoidAlgebra.coeff polynomial exponent)

/-- Exact kernel characterization of the joint nonlinear coefficient map. -/
theorem ker_coefficientFeature
    [Field K]
    (n : Nat) :
    LinearMap.ker (coefficientFeature (K := K) n) = affineSubmodule K n :=
  le_antisymm (ker_coefficientFeature_le_affineSubmodule n)
    (affineSubmodule_le_ker_coefficientFeature n)

/-- Full nonlinear coefficient matrix of an output family. -/
def coefficientMatrix
    [Field K]
    (n : Nat)
    (outputs : Fin m → MvPolynomial (Fin n) K) :
    Matrix (Exponent n) (Fin m) K :=
  Polynomial.coefficientMatrix
    (fun exponent : Exponent n => exponent.1) outputs

/-- Full nonlinear coefficient rank is exactly the canonical quotient-output
rank modulo affine-linear polynomials. -/
theorem coefficientMatrix_rank_eq_outputRank
    [Field K]
    (n : Nat)
    (outputs : Fin m → MvPolynomial (Fin n) K) :
    (coefficientMatrix (K := K) n outputs).rank =
      Linear.Quotient.outputRank (K := K)
        (MvPolynomial.C : K → MvPolynomial (Fin n) K)
        (inputProblem K n) outputs := by
  exact Polynomial.Quotient.coefficientMatrix_rank_eq_outputRank_of_ker_eq
    (fun scalar : K => scalar) (fun input : Fin n => input)
    (fun exponent : Exponent n => exponent.1)
    (fun exponent => exponent.2.1)
    (fun exponent input => exponent.2.2 input)
    (ker_coefficientFeature n) outputs

/-- Full nonlinear coefficient rank lower-bounds multiplication cost for
standard polynomial circuits with arbitrary field constants and cancellation. -/
theorem coefficientMatrix_rank_le_multiplicationCost
    [Field K]
    (n : Nat)
    (outputs : Fin m → MvPolynomial (Fin n) K)
    (circuit : Circuit (Algebraic.Arithmetic.signature K) n g m)
    (constructs : Multiple.Constructs
      (constant := (MvPolynomial.C : K → MvPolynomial (Fin n) K))
      (inputProblem K n) outputs circuit) :
    (coefficientMatrix (K := K) n outputs).rank ≤
      circuit.cost
        (Algebraic.Arithmetic.multiplicationCost (K := K)) := by
  rw [coefficientMatrix_rank_eq_outputRank]
  exact Linear.Quotient.outputRank_le_multiplicationCost
    (MvPolynomial.C : K → MvPolynomial (Fin n) K)
    (inputProblem K n) outputs circuit constructs

/-- Full nonlinear coefficient rank lower-bounds raw standard-circuit size. -/
theorem coefficientMatrix_rank_le_size
    [Field K]
    (n : Nat)
    (outputs : Fin m → MvPolynomial (Fin n) K)
    (circuit : Circuit (Algebraic.Arithmetic.signature K) n g m)
    (constructs : Multiple.Constructs
      (constant := (MvPolynomial.C : K → MvPolynomial (Fin n) K))
      (inputProblem K n) outputs circuit) :
    (coefficientMatrix (K := K) n outputs).rank ≤ circuit.size :=
  (coefficientMatrix_rank_le_multiplicationCost n outputs circuit
    constructs).trans
      ((Combined.circuit_multiplicationCost_le_gateCost circuit).trans
        (Combined.circuit_gateCost_le_size circuit))

end
end Nonlinear
end Polynomial
end Interaction
end Arithmetic
end Fusion
end Algebraic
