/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Complexitylib.Algebraic.LowerBound.Cutwidth.Aggregate.Geometry.Multioutput.Rank.Internal

/-!
# Affine functions and actual conjunction features span circuit outputs

The submodule generated by affine primary functions and actual conjunction gate
functions contains every gate, and hence every designated output wire.
-/

@[expose] public section

namespace Algebraic.Aggregate.Geometry

/-- Every output is an affine primary function plus a linear combination of the
actual conjunction gate functions. -/
theorem output_mem_affine_sup_conjunctionRange {n m : ℕ} (c : Circuit signature n m)
    (j : Fin m) :
    (fun x => bitValue (c.eval interpretation x j)) ∈ affineFunctions n ⊔
      (Fintype.linearCombination (ZMod 2)
        (fun i : {i : Fin c.size // (c.program.lines i).op.isConjunction = true} =>
          fun x => bitValue (c.program.gateFunction interpretation i x))).range := by
  classical
  let combination := Fintype.linearCombination (ZMod 2)
    (fun i : {i : Fin c.size // (c.program.lines i).op.isConjunction = true} =>
      fun x => bitValue (c.program.gateFunction interpretation i x))
  let S := affineFunctions n ⊔ combination.range
  have constants (b : ZMod 2) : (fun _ : Fin n → Bool => b) ∈ S :=
    Submodule.mem_sup_left ⟨b, 0, by ext; simp⟩
  have inputs (i : Fin n) : (fun x => bitValue (x i)) ∈ S :=
    Submodule.mem_sup_left ⟨0, LinearMap.proj i, by ext; simp [bitVector]⟩
  have gates := gateValues_mem c.program S constants inputs (by
    intro i hi
    apply Submodule.mem_sup_right
    refine ⟨Pi.single ⟨i, hi⟩ 1, ?_⟩
    simp [combination, Fintype.linearCombination_apply_single])
  change (fun x => bitValue
    (c.program.wireFunction interpretation (c.outputs j) x)) ∈ S
  cases c.outputs j with
  | input i => exact inputs i
  | gate i => exact gates i

end Algebraic.Aggregate.Geometry
